### ISSUE TITLE
ManagementClientProvider.onlineStandalone(managementClient) causes intermittent issue

### ISSUE THREAD

**Issue by istraka** [jboss-eap-qe/eap-microprofile-test-suite#170] opened 2020-01-14 11:57 UTC
Using `ManagementClientProvider.onlineStandalone(managementClient)` may results into an intermittent issue: http://pastebin.test.redhat.com/827086

The problem is Creaper check periodically client liveness and if it is down, it tries to reconnect. However this is not possible for wrapped client, see:
https://github.com/wildfly-extras/creaper/blob/master/core/src/main/java/org/wildfly/extras/creaper/core/online/OnlineManagementClientImpl.java#L221 

usage: http://pastebin.test.redhat.com/827084

**proposed solution**
use `ManagementClientProvider.onlineStandalone()` or `OnlineManagementClient onlineStandalone(ArquillianContainerProperties arquillianContainerProperties)`

**Comment by fabiobrz** [comment] 2020-01-14 19:27
Thanks @istraka, I'd like to hear from others, too but I'd go with your proposed solution as - although breaking the rule of using the `ManagementClient` instance provided by Arquillian in some cases as `ServerSetupTask` implementation - it would allow to execute the tests without any intermittent failure.

**Comment by mnovak1** [comment] 2020-01-15 09:54
I'll close this one as duplicate of https://github.com/jboss-eap-qe/eap-microprofile-test-suite/issues/169

**Closed by mnovak1** 2020-01-15 09:54 UTC
